# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Created on: 2020-05-25 12:39:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Defines projection WGS84 to all files inside a folder
# ---------------------------------------------------------------------------

# Import arcpy module

import arcpy
import os

# Getting the file names
basedir = 'C:\\Mega\\Work_files\\Results\\SBAS\\K-means\\'
files = os.listdir(basedir)
print(files)
# Define projection for all files as one after another
for file in files:
    curr_file = basedir + "\\" + file
    # Process: Define Projection
    arcpy.DefineProjection_management(curr_file, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
    print(curr_file)
